language: python
sudo: false
python:
- 2.7
- 3.7
matrix:
  fast_finish: true
  include:
  - python: pypy
    env: TEST_ENV=webpy_graphql
  - python: '2.7'
    env: TEST_ENV=webpy_graphql
  - python: '3.7'
    env: TEST_ENV=webpy_graphql
install:
- pip install -r requirements.txt
- pip install Paste
- pip install python-coveralls
- pip install nose
script:
- nosetests  --with-coverage --cover-package=tests
after_success:
- coveralls
deploy:
  provider: pypi
  user: igorkozintsev
  on:
    tags: true
